spring.application.name:
  forestworld-blog
server:
  port: 7002
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://101.200.158.94:9740/forestblog
    username: beiyouge
    password: AaZz123456
    # application.properties
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    root: info

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    operations-sorter: method
    enabled: true
    path: /swagger-ui.html

mybatis-plus:
  mapper-locations: classpath*:/dao/**/*.xml
